sudo: required
services:
  - docker

before_install:
  - docker build -t vinay0079/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vinay0079/react-test npm run test -- --coverage

after_success:
  - docker build -t vinay0079/multi-client ./client
  - docker build -t vinay0079/multi-nginx ./nginx
  - docker build -t vinay0079/multi-server ./server
  - docker build -t vinay0079/multi-worker ./worker
  # Log in to the docker client
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images to docker hub
  - docker push vinay0079/multi-client
  - docker push vinay0079/multi-nginx
  - docker push vinay0079/multi-server
  - docker push vinay0079/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker-app
  env: MultiDockerApp-env
  bucket_name: elasticbeanstalk-ap-south-1-185956305444
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
